// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUQsu4pKT4K5vUaxH_FYUb0dtxBZufe_U',
    appId: '1:683993489161:web:ea2ece61b0e59af1f83dd8',
    messagingSenderId: '683993489161',
    projectId: 'book-reader-app-c75ba',
    authDomain: 'book-reader-app-c75ba.firebaseapp.com',
    storageBucket: 'book-reader-app-c75ba.firebasestorage.app',
    measurementId: 'G-VZPBP06BBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVWP81ClVwpPydUmGLSaCpW5psg12pAUQ',
    appId: '1:683993489161:android:8174194286a3d60df83dd8',
    messagingSenderId: '683993489161',
    projectId: 'book-reader-app-c75ba',
    storageBucket: 'book-reader-app-c75ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlZOf4GQqEyXYXPIyYaYFZZQ4UR4THR1g',
    appId: '1:683993489161:ios:6208b487fb7e1055f83dd8',
    messagingSenderId: '683993489161',
    projectId: 'book-reader-app-c75ba',
    storageBucket: 'book-reader-app-c75ba.firebasestorage.app',
    iosClientId: '683993489161-5e1m0jp7timmmsopcpa271k927cqobha.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookReaderApp',
  );

}